# generated by datamodel-codegen:
#   filename:  client-control-plane.openapi.yaml
#   timestamp: 2026-01-29T04:23:03+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, Field


class Status(StrEnum):
    ok = 'ok'


class Service(StrEnum):
    detrix_client = 'detrix-client'


class HealthResponse(BaseModel):
    status: Annotated[
        Status,
        Field(
            description='Health status (always "ok" if the control plane is running)'
        ),
    ]
    service: Annotated[Service, Field(description='Service identifier')]


class InfoResponse(BaseModel):
    name: Annotated[
        str,
        Field(
            description='Connection name for this client', examples=['my-service-12345']
        ),
    ]
    pid: Annotated[int, Field(description='Process ID of the client', examples=[12345])]
    python_version: Annotated[
        str | None,
        Field(
            description='Python version (Python client only)',
            examples=['3.12.0 (main, Oct  2 2023, 00:00:00)'],
        ),
    ] = None
    python_executable: Annotated[
        str | None,
        Field(
            description='Python executable path (Python client only)',
            examples=['/usr/bin/python3'],
        ),
    ] = None
    go_version: Annotated[
        str | None,
        Field(description='Go version (Go client only)', examples=['go1.22.0']),
    ] = None
    rust_version: Annotated[
        str | None,
        Field(description='Rust version (Rust client only)', examples=['1.75.0']),
    ] = None


class WakeRequest(BaseModel):
    daemon_url: Annotated[
        AnyUrl | None,
        Field(
            description='Override the daemon URL for this wake operation.\nIf not provided, uses the URL configured during init().\n',
            examples=['http://192.168.1.100:8090'],
        ),
    ] = None


class Status1(StrEnum):
    awake = 'awake'
    already_awake = 'already_awake'


class WakeResponse(BaseModel):
    status: Annotated[
        Status1,
        Field(
            description='"awake" if the client transitioned from sleeping to awake.\n"already_awake" if the client was already in awake state.\n'
        ),
    ]
    debug_port: Annotated[
        int,
        Field(
            description='Port the debug adapter is listening on',
            examples=[5678],
            ge=1,
            le=65535,
        ),
    ]
    connection_id: Annotated[
        str,
        Field(
            description='Connection ID assigned by the daemon', examples=['conn_abc123']
        ),
    ]


class Status2(StrEnum):
    sleeping = 'sleeping'
    already_sleeping = 'already_sleeping'


class SleepResponse(BaseModel):
    status: Annotated[
        Status2,
        Field(
            description='"sleeping" if the client transitioned from awake to sleeping.\n"already_sleeping" if the client was already in sleeping state.\n'
        ),
    ]


class ClientState(StrEnum):
    sleeping = 'sleeping'
    waking = 'waking'
    awake = 'awake'


class ErrorResponse(BaseModel):
    error: Annotated[
        str,
        Field(
            description='Error message',
            examples=['Daemon not reachable at http://127.0.0.1:8090'],
        ),
    ]


class StatusResponse(BaseModel):
    state: ClientState
    name: Annotated[
        str,
        Field(
            description='Connection name for this client', examples=['my-service-12345']
        ),
    ]
    control_host: Annotated[
        str,
        Field(description='Host the control plane is bound to', examples=['127.0.0.1']),
    ]
    control_port: Annotated[
        int,
        Field(
            description='Actual port the control plane is listening on.\n0 if the control plane has not been started yet.\n',
            examples=[8091],
            ge=0,
            le=65535,
        ),
    ]
    debug_port: Annotated[
        int,
        Field(
            description='Debug adapter port. 0 if debugger has never been started.\nMay be non-zero even when sleeping due to debugger limitations.\n',
            examples=[5678],
            ge=0,
            le=65535,
        ),
    ]
    debug_port_active: Annotated[
        bool,
        Field(
            description='True if the debug port is actually open and accepting connections.\nThis may be true even when state is "sleeping" because some debuggers\n(e.g., debugpy) cannot stop their listener once started.\n',
            examples=[True],
        ),
    ]
    daemon_url: Annotated[
        str,
        Field(
            description='URL of the Detrix daemon this client connects to',
            examples=['http://127.0.0.1:8090'],
        ),
    ]
    connection_id: Annotated[
        str | None,
        Field(
            description='Connection ID assigned by the daemon upon registration.\nNull if not currently registered (state is "sleeping").\n',
            examples=['conn_abc123'],
        ),
    ]
