//! Ring buffer reader — converts raw BPF events to ProbeEvents
//!
//! On Linux, reads from BPF_MAP_TYPE_RINGBUF via aya.
//! Cross-platform: the parsing logic is testable anywhere.
//!
//! # Nested Struct Support
//!
//! Struct fields are captured sequentially in the ring buffer.
//! For a struct with N fields, the layout is:
//! ```text
//! var{idx} (u64) - base address or first field
//! var{idx}_field0 - field 0 value
//! var{idx}_field1 - field 1 value (or blob for nested data)
//! ...
//! ```
//!
//! The parser reconstructs `CapturedValue::Struct` by:
//! 1. Reading field count from DWARF type info
//! 2. Parsing each field value recursively
//! 3. Building nested `CapturedValue::Struct` hierarchy

use crate::dwarf::nested_types::NestedType;
use crate::dwarf::types::ResolvedVariable;
use crate::error::{Error, Result};
use crate::mem_reader::ProcessMemoryReader;
use crate::probe::types::{CaptureConfig, CapturedValue, ProbeEvent};

/// Minimum event size: pid(4) + tid(4) + timestamp(8) = 16 bytes.
const MIN_EVENT_SIZE: usize = 16;

/// Parse a raw ring buffer entry into a ProbeEvent.
///
/// The binary layout matches the `struct probe_event` generated by
/// `probe::program::generate_bpf_program`. Fields are little-endian,
/// naturally aligned.
///
/// Layout:
/// ```text
/// offset 0:  u32 pid
/// offset 4:  u32 tid
/// offset 8:  u64 goid        (if capture_goid)
/// offset N:  u64 timestamp
/// offset N+8: u64 var0
/// ...
/// ```
pub fn parse_ring_buffer_event(
    data: &[u8],
    variables: &[ResolvedVariable],
    capture_goid: bool,
    config: &CaptureConfig,
    mem_reader: &dyn ProcessMemoryReader,
) -> Result<ProbeEvent> {
    if data.len() < MIN_EVENT_SIZE {
        return Err(Error::RingBuffer(format!(
            "Event too small: {} bytes (min {MIN_EVENT_SIZE})",
            data.len()
        )));
    }

    let mut offset = 0;

    let pid = read_u32(data, &mut offset)?;
    let tid = read_u32(data, &mut offset)?;

    let goid = if capture_goid {
        Some(read_u64(data, &mut offset)?)
    } else {
        None
    };

    let timestamp_ns = read_u64(data, &mut offset)?;

    let mut values = Vec::with_capacity(variables.len());
    for var in variables {
        let val = read_u64(data, &mut offset).unwrap_or(0);
        let captured = match &var.location {
            crate::dwarf::types::VariableLocation::GoString { .. } => {
                // Read string length from the event (BPF read this from stack)
                let len = read_u64(data, &mut offset).unwrap_or(0) as usize;
                // Skip the empty buffer (BPF doesn't read Go heap)
                let _ = read_bytes(data, &mut offset, config.max_string_capture);

                // ALWAYS use user-space memory reader for Go strings
                // BPF cannot access Go heap memory reliably
                detrix_logging::debug!(
                    "[ringbuf] Reading Go string via user-space: pid={} ptr={:#x} len={}",
                    pid,
                    val,
                    len
                );

                // Try with pid first, then tid
                let mut result = mem_reader.read_string(pid, val, len);
                if result.is_err() {
                    result = mem_reader.read_string(tid, val, len);
                }

                match result {
                    Ok(s) => CapturedValue::String {
                        data: s.into_bytes(),
                        len,
                    },
                    Err(e) => {
                        detrix_logging::warn!(
                            "[ringbuf] Failed to read Go string: pid={} tid={} ptr={:#x} len={}: {}",
                            pid, tid, val, len, e
                        );
                        CapturedValue::String {
                            data: b"<read-failed>".to_vec(),
                            len,
                        }
                    }
                }
            }
            crate::dwarf::types::VariableLocation::GoSlice { .. } => {
                let len = read_u64(data, &mut offset).unwrap_or(0);
                let cap = read_u64(data, &mut offset).unwrap_or(0);
                CapturedValue::Slice { len, cap }
            }
            crate::dwarf::types::VariableLocation::StackBlob { byte_size, .. } => {
                // var{idx} (u64) was already read above as `val` — it is 0 (unused).
                // The BPF program filled var{idx}_blob[N] with the actual bytes inline.
                let capture = (*byte_size).min(config.max_blob_capture);
                let bytes =
                    read_bytes(data, &mut offset, capture).unwrap_or_else(|_| vec![0u8; capture]);

                // If we have DWARF field info, parse the blob into named fields
                if let Some(crate::dwarf::nested_types::NestedType::Struct {
                    fields: dwarf_fields,
                    ..
                }) = &var.nested_type
                {
                    parse_struct_fields_from_blob(
                        &bytes,
                        &var.type_name,
                        dwarf_fields,
                        config,
                        mem_reader,
                        pid,
                    )
                } else {
                    CapturedValue::Bytes(bytes)
                }
            }
            crate::dwarf::types::VariableLocation::StackIndirect { byte_size, .. } => {
                // `val` holds the pointer read from the stack slot by BPF.
                // Heap-escaped Go struct: dereference the pointer in user-space to read
                // the actual struct bytes, then parse fields using DWARF type info.
                detrix_logging::debug!(
                    "[ringbuf] StackIndirect '{}': ptr={:#x} byte_size={}",
                    var.name,
                    val,
                    byte_size
                );
                let capture = (*byte_size).min(config.max_blob_capture);
                let bytes = if val != 0 {
                    let mut result = mem_reader.read_bytes(pid, val, capture);
                    if result.is_err() {
                        result = mem_reader.read_bytes(tid, val, capture);
                    }
                    result.unwrap_or_else(|_| vec![0u8; capture])
                } else {
                    vec![0u8; capture]
                };

                if let Some(crate::dwarf::nested_types::NestedType::Struct {
                    fields: dwarf_fields,
                    ..
                }) = &var.nested_type
                {
                    parse_struct_fields_from_blob(
                        &bytes,
                        &var.type_name,
                        dwarf_fields,
                        config,
                        mem_reader,
                        pid,
                    )
                } else {
                    CapturedValue::Bytes(bytes)
                }
            }
            _ => {
                // Check if this is a struct type by checking if we have nested type info
                // DWARF resolution populates nested_type for struct types
                detrix_logging::debug!(
                    "[ringbuf] Variable '{}' type='{}' nested_type={:?}",
                    var.name,
                    var.type_name,
                    var.nested_type.as_ref().map(|_| "Some")
                );
                if var.nested_type.is_some() {
                    // For structs, BPF captured the base address as `val` (the u64 we already read)
                    // We need to use that address to read fields from user-space
                    // Don't read more from ring buffer - use `val` as the struct base address
                    parse_struct_fields_from_addr(
                        val, // Use the value BPF already captured as struct base address
                        &var.type_name,
                        config,
                        var.nested_type.as_ref(),
                        mem_reader,
                        pid,
                    )?
                } else {
                    CapturedValue::Scalar(val)
                }
            }
        };
        values.push(captured);
    }

    Ok(ProbeEvent {
        pid,
        tid,
        goid,
        timestamp_ns,
        values,
    })
}

fn read_bytes(data: &[u8], offset: &mut usize, count: usize) -> Result<Vec<u8>> {
    if *offset + count > data.len() {
        return Err(Error::RingBuffer(format!(
            "Unexpected end of event reading {count} bytes at offset {offset}"
        )));
    }
    let bytes = data[*offset..*offset + count].to_vec();
    *offset += count;
    Ok(bytes)
}

fn read_u32(data: &[u8], offset: &mut usize) -> Result<u32> {
    if *offset + 4 > data.len() {
        return Err(Error::RingBuffer(format!(
            "Unexpected end of event at offset {offset}"
        )));
    }
    let val = u32::from_le_bytes(
        data[*offset..*offset + 4]
            .try_into()
            .map_err(|_| Error::RingBuffer("u32 parse failed".to_string()))?,
    );
    *offset += 4;
    Ok(val)
}

fn read_u64(data: &[u8], offset: &mut usize) -> Result<u64> {
    if *offset + 8 > data.len() {
        return Err(Error::RingBuffer(format!(
            "Unexpected end of event at offset {offset}"
        )));
    }
    let val = u64::from_le_bytes(
        data[*offset..*offset + 8]
            .try_into()
            .map_err(|_| Error::RingBuffer("u64 parse failed".to_string()))?,
    );
    *offset += 8;
    Ok(val)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dwarf::types::{Register, ResolvedVariable, VariableLocation, VariableSize};
    use crate::probe::types::{CaptureConfig, MAX_STRING_CAPTURE};

    /// Stub memory reader for tests - returns strings based on pointer value
    struct StubMemReader;
    impl ProcessMemoryReader for StubMemReader {
        fn read_string(&self, _pid: u32, ptr: u64, len: usize) -> Result<String> {
            // Return specific test strings based on pointer address
            match ptr {
                0xDEADBEEF => Ok("hello".to_string()),
                0xCAFEBABE => Ok("BTCUSD".to_string()),
                _ => Ok(std::iter::repeat('x').take(len).collect()),
            }
        }

        fn read_bytes(&self, _pid: u32, _ptr: u64, len: usize) -> Result<Vec<u8>> {
            Ok(vec![0u8; len])
        }

        fn read_u64(&self, _pid: u32, _ptr: u64) -> Result<u64> {
            Ok(0)
        }
    }

    fn build_event_bytes(pid: u32, tid: u32, timestamp: u64, var_values: &[u64]) -> Vec<u8> {
        let mut buf = Vec::new();
        buf.extend_from_slice(&pid.to_le_bytes());
        buf.extend_from_slice(&tid.to_le_bytes());
        buf.extend_from_slice(&timestamp.to_le_bytes());
        for v in var_values {
            buf.extend_from_slice(&v.to_le_bytes());
        }
        buf
    }

    fn build_event_bytes_with_goid(
        pid: u32,
        tid: u32,
        goid: u64,
        timestamp: u64,
        var_values: &[u64],
    ) -> Vec<u8> {
        let mut buf = Vec::new();
        buf.extend_from_slice(&pid.to_le_bytes());
        buf.extend_from_slice(&tid.to_le_bytes());
        buf.extend_from_slice(&goid.to_le_bytes());
        buf.extend_from_slice(&timestamp.to_le_bytes());
        for v in var_values {
            buf.extend_from_slice(&v.to_le_bytes());
        }
        buf
    }

    fn scalar_var(name: &str) -> ResolvedVariable {
        ResolvedVariable {
            name: name.to_string(),
            location: VariableLocation::Register(Register::Rax),
            size: VariableSize::QWord,
            type_name: "int64".to_string(),
            nested_type: None,
        }
    }

    #[test]
    fn parse_empty_event_no_vars() {
        let data = build_event_bytes(1000, 2000, 5_000_000_000, &[]);
        let event =
            parse_ring_buffer_event(&data, &[], false, &CaptureConfig::default(), &StubMemReader)
                .unwrap();

        assert_eq!(event.pid, 1000);
        assert_eq!(event.tid, 2000);
        assert_eq!(event.goid, None);
        assert_eq!(event.timestamp_ns, 5_000_000_000);
        assert!(event.values.is_empty());
    }

    #[test]
    fn parse_single_scalar_var() {
        let data = build_event_bytes(1, 2, 100, &[42]);
        let vars = vec![scalar_var("amount")];
        let event = parse_ring_buffer_event(
            &data,
            &vars,
            false,
            &CaptureConfig::default(),
            &StubMemReader,
        )
        .unwrap();

        assert_eq!(event.values.len(), 1);
        assert_eq!(event.values[0].as_u64(), Some(42));
    }

    #[test]
    fn parse_multiple_vars() {
        let data = build_event_bytes(1, 2, 100, &[10, 20, 30]);
        let vars = vec![scalar_var("a"), scalar_var("b"), scalar_var("c")];
        let event = parse_ring_buffer_event(
            &data,
            &vars,
            false,
            &CaptureConfig::default(),
            &StubMemReader,
        )
        .unwrap();

        assert_eq!(event.values.len(), 3);
        assert_eq!(event.values[0].as_u64(), Some(10));
        assert_eq!(event.values[1].as_u64(), Some(20));
        assert_eq!(event.values[2].as_u64(), Some(30));
    }

    #[test]
    fn parse_with_goid() {
        let data = build_event_bytes_with_goid(1, 2, 999, 100, &[42]);
        let vars = vec![scalar_var("x")];
        let event = parse_ring_buffer_event(
            &data,
            &vars,
            true,
            &CaptureConfig::default(),
            &StubMemReader,
        )
        .unwrap();

        assert_eq!(event.goid, Some(999));
        assert_eq!(event.values[0].as_u64(), Some(42));
    }

    #[test]
    fn parse_too_small_fails() {
        let data = vec![0u8; 10]; // Less than MIN_EVENT_SIZE
        let result =
            parse_ring_buffer_event(&data, &[], false, &CaptureConfig::default(), &StubMemReader);
        assert!(result.is_err());
    }

    #[test]
    fn parse_truncated_var_data() {
        // Event with header but missing variable data
        let data = build_event_bytes(1, 2, 100, &[]);
        let vars = vec![scalar_var("x")]; // Expects 8 more bytes
        let event = parse_ring_buffer_event(
            &data,
            &vars,
            false,
            &CaptureConfig::default(),
            &StubMemReader,
        )
        .unwrap();
        // Should handle gracefully with default value
        assert_eq!(event.values[0].as_u64(), Some(0));
    }

    #[test]
    fn parse_go_string_var() {
        let mut data = build_event_bytes(1, 2, 100, &[]);
        // String pointer - stub reader returns "hello" for this address
        data.extend_from_slice(&0xDEADBEEF_u64.to_le_bytes());
        // String length
        data.extend_from_slice(&5_u64.to_le_bytes());
        // Skip buffer - memory reader provides content now
        data.extend_from_slice(&vec![0u8; MAX_STRING_CAPTURE]);

        let vars = vec![ResolvedVariable {
            name: "name".to_string(),
            location: VariableLocation::GoString {
                ptr: Box::new(VariableLocation::Register(Register::Rax)),
                len: Box::new(VariableLocation::Register(Register::Rbx)),
            },
            size: VariableSize::QWord,
            type_name: "string".to_string(),
            nested_type: None,
        }];

        let event = parse_ring_buffer_event(
            &data,
            &vars,
            false,
            &CaptureConfig::default(),
            &StubMemReader,
        )
        .unwrap();
        assert_eq!(event.values.len(), 1);
        match &event.values[0] {
            CapturedValue::String { len, data } => {
                assert_eq!(*len, 5);
                assert_eq!(data, b"hello");
            }
            other => panic!("Expected String, got {other:?}"),
        }
    }

    #[test]
    fn parse_go_string_with_symbol_content() {
        let symbol = b"BTCUSD";
        let mut data = build_event_bytes(1, 2, 100, &[]);
        data.extend_from_slice(&0xCAFEBABE_u64.to_le_bytes()); // ptr - stub returns "BTCUSD"
        data.extend_from_slice(&(symbol.len() as u64).to_le_bytes()); // len
                                                                      // Skip buffer - memory reader provides content now
        data.extend_from_slice(&vec![0u8; MAX_STRING_CAPTURE]);

        let vars = vec![ResolvedVariable {
            name: "symbol".to_string(),
            location: VariableLocation::GoString {
                ptr: Box::new(VariableLocation::Register(Register::Rax)),
                len: Box::new(VariableLocation::Register(Register::Rbx)),
            },
            size: VariableSize::QWord,
            type_name: "string".to_string(),
            nested_type: None,
        }];

        let event = parse_ring_buffer_event(
            &data,
            &vars,
            false,
            &CaptureConfig::default(),
            &StubMemReader,
        )
        .unwrap();
        match &event.values[0] {
            CapturedValue::String { len, data } => {
                assert_eq!(*len, 6);
                assert_eq!(std::str::from_utf8(data).unwrap(), "BTCUSD");
            }
            other => panic!("Expected String, got {other:?}"),
        }
    }

    #[test]
    fn parse_go_slice_returns_len_and_cap() {
        let mut data = build_event_bytes(1, 2, 100, &[]);
        data.extend_from_slice(&0xDEAD_u64.to_le_bytes()); // ptr (var0)
        data.extend_from_slice(&7_u64.to_le_bytes()); // len (var0_len)
        data.extend_from_slice(&16_u64.to_le_bytes()); // cap (var0_cap)

        let vars = vec![ResolvedVariable {
            name: "items".to_string(),
            location: VariableLocation::GoSlice {
                ptr: Box::new(VariableLocation::Register(Register::Rax)),
                len: Box::new(VariableLocation::Register(Register::Rbx)),
                cap: Box::new(VariableLocation::Register(Register::Rcx)),
            },
            size: VariableSize::QWord,
            type_name: "[]int64".to_string(),
            nested_type: None,
        }];

        let event = parse_ring_buffer_event(
            &data,
            &vars,
            false,
            &CaptureConfig::default(),
            &StubMemReader,
        )
        .unwrap();
        match &event.values[0] {
            CapturedValue::Slice { len, cap } => {
                assert_eq!(*len, 7);
                assert_eq!(*cap, 16);
            }
            other => panic!("Expected Slice, got {other:?}"),
        }
    }

    #[test]
    fn parse_stack_blob_returns_bytes() {
        let blob: [u8; 4] = [0xDE, 0xAD, 0xBE, 0xEF];
        let mut data = build_event_bytes(1, 2, 100, &[]);
        data.extend_from_slice(&0_u64.to_le_bytes()); // var0 (unused for blobs)
        data.extend_from_slice(&blob); // var0_blob[4]

        let vars = vec![ResolvedVariable {
            name: "req".to_string(),
            location: VariableLocation::StackBlob {
                offset: -32,
                byte_size: 4,
            },
            size: VariableSize::QWord,
            type_name: "TradeRequest".to_string(),
            nested_type: None,
        }];

        let config = CaptureConfig {
            max_capture_vars: 8,
            max_string_capture: 64,
            max_blob_capture: 64,
            ..CaptureConfig::default()
        };
        let event = parse_ring_buffer_event(&data, &vars, false, &config, &StubMemReader).unwrap();
        match &event.values[0] {
            CapturedValue::Bytes(b) => {
                assert_eq!(b.as_slice(), &blob);
            }
            other => panic!("Expected Bytes, got {other:?}"),
        }
    }

    #[test]
    fn parse_stack_blob_clamped_to_max_blob_capture() {
        // byte_size=32 but max_blob_capture=4 — only 4 bytes should be read
        let mut data = build_event_bytes(1, 2, 100, &[]);
        data.extend_from_slice(&0_u64.to_le_bytes()); // var0 unused
        data.extend_from_slice(&[1u8, 2, 3, 4]); // only 4 bytes in event

        let vars = vec![ResolvedVariable {
            name: "big".to_string(),
            location: VariableLocation::StackBlob {
                offset: 0,
                byte_size: 32,
            },
            size: VariableSize::QWord,
            type_name: "[4]int64".to_string(),
            nested_type: None,
        }];

        let config = CaptureConfig {
            max_capture_vars: 8,
            max_string_capture: 64,
            max_blob_capture: 4,
            ..CaptureConfig::default()
        };
        let event = parse_ring_buffer_event(&data, &vars, false, &config, &StubMemReader).unwrap();
        match &event.values[0] {
            CapturedValue::Bytes(b) => {
                assert_eq!(b.len(), 4);
                assert_eq!(b.as_slice(), &[1u8, 2, 3, 4]);
            }
            other => panic!("Expected Bytes, got {other:?}"),
        }
    }

    #[test]
    fn slice_len_accessor() {
        let val = CapturedValue::Slice { len: 5, cap: 10 };
        assert_eq!(val.slice_len(), Some(5));
    }

    #[test]
    fn bytes_accessor() {
        let val = CapturedValue::Bytes(vec![0xAB, 0xCD]);
        assert_eq!(val.as_bytes(), Some([0xABu8, 0xCD].as_ref()));
    }
}

// ============================================================================
// Nested struct support
// ============================================================================

/// Walk through `NestedType::Pointer` wrappers to find the first `Struct` variant.
///
/// Go's cross-CU pointer types can produce double-wrapped Pointer nodes
/// (the outer one from the member's DW_AT_type, the inner from the pointer type entry).
/// This unwraps all pointer layers to get to the actual struct fields and type name.
fn find_struct_pointee(
    nested: &crate::dwarf::nested_types::NestedType,
) -> Option<(&str, &[crate::dwarf::nested_types::StructField])> {
    let mut current = nested;
    loop {
        match current {
            crate::dwarf::nested_types::NestedType::Pointer { pointee, .. } => {
                current = pointee.as_ref();
            }
            crate::dwarf::nested_types::NestedType::Struct {
                type_info, fields, ..
            } => {
                return Some((type_info.name.as_str(), fields.as_slice()));
            }
            _ => return None,
        }
    }
}

/// Parse `map[K]V` or `map<K,V>` into (key_str, val_str).
fn parse_map_type_names(type_name: &str) -> (String, String) {
    if let Some(inner) = type_name.strip_prefix("map[") {
        if let Some(bracket_end) = inner.find(']') {
            let key = &inner[..bracket_end];
            let val = &inner[bracket_end + 1..];
            return (key.to_string(), val.to_string());
        }
    }
    if let Some(inner) = type_name.strip_prefix("map<") {
        if let Some(comma) = inner.find(',') {
            if let Some(gt) = inner.find('>') {
                let key = inner[..comma].trim();
                let val = inner[comma + 1..gt].trim();
                return (key.to_string(), val.to_string());
            }
        }
    }
    ("unknown".to_string(), "unknown".to_string())
}

/// Check if a type name indicates a struct type.
///
/// Go struct types from DWARF have names like:
/// - "main.Order" (with package prefix)
/// - "Order" (just the type name)
/// - "struct { ... }" (anonymous structs)
///
/// Excludes:
/// - Slice types: "[]T"
/// - Map types: "map[K]V"
/// - Pointer types: "*T"
/// - Basic types: "int", "string", "bool", etc.
#[allow(dead_code)]
fn is_struct_type(type_name: &str) -> bool {
    // Skip slices, maps, pointers
    if type_name.starts_with("[]") || type_name.starts_with("map[") || type_name.starts_with('*') {
        return false;
    }

    // Skip basic types
    let basic_types = [
        "int",
        "int8",
        "int16",
        "int32",
        "int64",
        "uint",
        "uint8",
        "uint16",
        "uint32",
        "uint64",
        "uintptr",
        "float32",
        "float64",
        "complex64",
        "complex128",
        "bool",
        "string",
        "byte",
        "rune",
        "error",
    ];
    if basic_types.contains(&type_name) {
        return false;
    }

    // Struct types have package prefix (main.Order), simple name (Order), or are anonymous structs
    type_name.contains('.')
        || type_name.starts_with("struct")
        || (!type_name.is_empty() && !type_name.starts_with('[') && !type_name.starts_with("map"))
}

/// Parse struct fields using a known base address (captured by BPF).
///
/// BPF captures the struct base address as a u64.
/// We use DWARF type info to read each field from user-space memory.
///
/// This follows the same pattern as string capture:
/// 1. BPF captures base address from stack (as u64 in ring buffer)
/// 2. User-space reads DWARF field offsets
/// 3. User-space reads each field via process_vm_readv(base_addr + field_offset)

/// Parse a single slice/array element based on its NestedType.
/// Following Delve's loadArrayValues which creates a new variable for each element
/// and recursively loads its value with incremented recursion level.
fn parse_slice_element(
    elem_addr: u64,
    element_nested_type: &NestedType,
    element_size: u64,
    config: &CaptureConfig,
    mem_reader: &dyn crate::mem_reader::ProcessMemoryReader,
    pid: u32,
) -> Result<CapturedValue> {
    detrix_logging::debug!(
        "[ringbuf] parse_slice_element: addr={:#x}, type={:?}, size={}",
        elem_addr,
        match element_nested_type {
            NestedType::Struct { type_info, .. } => format!("Struct({})", type_info.name),
            NestedType::Scalar(t) => format!("Scalar({})", t.name),
            NestedType::Array { type_info, .. } => format!("Array({})", type_info.name),
            NestedType::Pointer { type_info, .. } => format!("Pointer({})", type_info.name),
            _ => "Other".to_string(),
        },
        element_size
    );

    match element_nested_type {
        NestedType::Struct { type_info, .. } => {
            // Element is a struct - recursively parse its fields
            // Following Delve: fieldvar.loadValueInternal(recurseLevel+1, cfg)
            parse_struct_fields_from_addr(
                elem_addr,
                &type_info.name,
                config,
                Some(element_nested_type),
                mem_reader,
                pid,
            )
        }
        NestedType::Scalar(type_info) => {
            // Element is a scalar - read based on type
            if type_info.is_string {
                // String element - read ptr+len and then content
                let str_ptr = mem_reader.read_u64(pid, elem_addr).unwrap_or(0);
                let str_len = mem_reader.read_u64(pid, elem_addr + 8).unwrap_or(0) as usize;
                if str_ptr != 0 && str_len > 0 {
                    match mem_reader.read_string(
                        pid,
                        str_ptr,
                        str_len.min(config.max_string_capture),
                    ) {
                        Ok(s) => Ok(CapturedValue::String {
                            len: s.len(),
                            data: s.into_bytes(),
                        }),
                        Err(_) => Ok(CapturedValue::String {
                            data: b"<read-failed>".to_vec(),
                            len: str_len,
                        }),
                    }
                } else {
                    Ok(CapturedValue::String {
                        data: vec![],
                        len: 0,
                    })
                }
            } else if type_info.name == "float64" {
                // Float64 element
                let val = mem_reader.read_u64(pid, elem_addr).unwrap_or(0);
                Ok(CapturedValue::Float(f64::from_bits(val)))
            } else if type_info.name == "float32" {
                // Float32 element - read as u64 and take lower 32 bits
                let val = mem_reader.read_u64(pid, elem_addr).unwrap_or(0);
                Ok(CapturedValue::Float(f32::from_bits(val as u32) as f64))
            } else {
                // Other scalar - read as integer
                let val = mem_reader.read_u64(pid, elem_addr).unwrap_or(0);
                Ok(CapturedValue::Scalar(val))
            }
        }
        NestedType::Pointer { pointee: _, .. } => {
            // Element is a pointer - read the address
            let ptr_val = mem_reader.read_u64(pid, elem_addr).unwrap_or(0);
            if ptr_val != 0 {
                // Could recursively follow the pointer if needed
                // For now, just return the pointer value
                Ok(CapturedValue::Scalar(ptr_val))
            } else {
                Ok(CapturedValue::Scalar(0))
            }
        }
        _ => {
            // Unknown element type - read as bytes
            match mem_reader.read_bytes(pid, elem_addr, element_size as usize) {
                Ok(bytes) => Ok(CapturedValue::Bytes(bytes)),
                Err(_) => Ok(CapturedValue::Error("read failed".to_string())),
            }
        }
    }
}

/// Parse struct fields from ring buffer data using user-space memory reading.
pub fn parse_struct_fields_from_addr(
    struct_base_addr: u64, // Base address captured by BPF
    type_name: &str,
    config: &CaptureConfig,
    nested_type: Option<&crate::dwarf::nested_types::NestedType>,
    mem_reader: &dyn crate::mem_reader::ProcessMemoryReader,
    pid: u32,
) -> Result<CapturedValue> {
    detrix_logging::debug!(
        "[ringbuf] Parsing struct fields for type '{}' at base addr {:#x} via user-space",
        type_name,
        struct_base_addr
    );

    // If struct address is 0 (nil pointer), return empty struct
    if struct_base_addr == 0 {
        return Ok(CapturedValue::Struct {
            type_name: type_name.to_string(),
            fields: vec![],
        });
    }

    // Heap-escaped Go variables have DWARF type `*T` (pointer to T).
    // The BPF ring buffer captures the pointer value (which IS the struct address on the heap).
    // Transparently unwrap one pointer level so we parse the pointee struct directly.
    if let Some(crate::dwarf::nested_types::NestedType::Pointer { pointee, .. }) = nested_type {
        let pointee_name = pointee.type_info().name.clone();
        match pointee.as_ref() {
            crate::dwarf::nested_types::NestedType::Struct { fields, .. } => {
                let items_nested = fields
                    .iter()
                    .find(|f| f.name == "Items")
                    .map(|f| f.nested_type.is_some());
                detrix_logging::debug!(
                    "[ringbuf] Unwrapping pointer for '{}', pointee type={}, pointee has {} fields, Items.has_nested={:?}",
                    type_name, pointee_name, fields.len(), items_nested
                );
            }
            _ => {}
        }
        return parse_struct_fields_from_addr(
            struct_base_addr,
            &pointee_name,
            config,
            Some(pointee.as_ref()),
            mem_reader,
            pid,
        );
    }

    let mut fields = Vec::new();

    // Use DWARF type info if available
    if let Some(crate::dwarf::nested_types::NestedType::Struct {
        fields: dwarf_fields,
        ..
    }) = nested_type
    {
        // Read each field from user-space memory
        for (field_idx, field) in dwarf_fields.iter().enumerate() {
            // Apply max_struct_fields limit
            if config.max_struct_fields >= 0 && field_idx >= config.max_struct_fields as usize {
                break;
            }

            let field_name = field.name.clone();
            let field_addr = struct_base_addr + field.byte_offset;

            detrix_logging::debug!(
                "[ringbuf] Reading field '{}' at {:#x} (type: {}, is_string={}, is_slice={}, is_array={})",
                field_name, field_addr, field.type_info.name, field.type_info.is_string, field.type_info.is_slice, field.type_info.is_array
            );

            // Parse field based on its type
            let field_value = if field.type_info.is_string {
                // String field: read ptr and len from user-space, then read content
                let str_ptr = mem_reader.read_u64(pid, field_addr).unwrap_or(0);
                let str_len = mem_reader.read_u64(pid, field_addr + 8).unwrap_or(0) as usize;

                if str_ptr != 0 && str_len > 0 {
                    match mem_reader.read_string(pid, str_ptr, str_len) {
                        Ok(s) => CapturedValue::String {
                            data: s.into_bytes(),
                            len: str_len,
                        },
                        Err(e) => {
                            detrix_logging::debug!(
                                "[ringbuf] Failed to read struct string field '{}': {}",
                                field_name,
                                e
                            );
                            CapturedValue::String {
                                data: b"<read-failed>".to_vec(),
                                len: str_len,
                            }
                        }
                    }
                } else {
                    CapturedValue::String {
                        data: vec![],
                        len: 0,
                    }
                }
            } else if field.type_info.is_slice {
                // Slice field: read {ptr, len, cap} header and elements
                // Following Delve's loadSliceInfo + loadArrayValues
                // Go slice header: ptr (8 bytes) + len (8 bytes) + cap (8 bytes) = 24 bytes
                let slice_ptr = mem_reader.read_u64(pid, field_addr).unwrap_or(0);
                let slice_len = mem_reader.read_u64(pid, field_addr + 8).unwrap_or(0);
                let slice_cap = mem_reader.read_u64(pid, field_addr + 16).unwrap_or(0);

                detrix_logging::debug!(
                    "[ringbuf] Slice field '{}' ptr={:#x} len={} cap={}, has_nested={}, nested_type_variant={:?}, field_nested_type={:?}",
                    field_name, slice_ptr, slice_len, slice_cap, field.nested_type.is_some(),
                    field.nested_type.as_ref().map(|n| match n {
                        NestedType::Array { element_type, .. } => format!("Array(element={})", element_type.type_info().name),
                        NestedType::Struct { type_info, .. } => format!("Struct({})", type_info.name),
                        NestedType::Scalar(t) => format!("Scalar({})", t.name),
                        NestedType::Pointer { .. } => "Pointer".to_string(),
                        NestedType::Map { .. } => "Map".to_string(),
                        NestedType::Interface { .. } => "Interface".to_string(),
                        NestedType::Unsupported { reason, .. } => format!("Unsupported({})", reason),
                    }),
                    field.nested_type.as_ref().map(|n| std::mem::discriminant(n))
                );

                // Read slice elements if we have a valid pointer and length
                if slice_ptr != 0 && slice_len > 0 && slice_len <= 10 {
                    // Limit to 10 elements to avoid excessive memory reads
                    // Get element size from the element type's TypeInfo
                    let element_size =
                        if let Some(NestedType::Array { element_type, .. }) = &field.nested_type {
                            // Use the element type's byte_size
                            element_type.type_info().byte_size.max(1)
                        } else if field.type_info.element_byte_size > 0 {
                            field.type_info.element_byte_size
                        } else if field.type_info.name.contains("OrderItem") {
                            // Fallback for known types
                            328 // OrderItem: Product(312) + Quantity(8) + Total(8)
                        } else {
                            8 // Default fallback
                        };

                    detrix_logging::debug!(
                        "[ringbuf] Reading {} slice elements, size={}, nested_type={:?}",
                        slice_len,
                        element_size,
                        field.nested_type.as_ref().map(|n| match n {
                            NestedType::Array { .. } => "Array",
                            NestedType::Struct { .. } => "Struct",
                            NestedType::Scalar(_) => "Scalar",
                            _ => "Other",
                        })
                    );

                    let mut elements = Vec::new();
                    for i in 0..slice_len {
                        let elem_addr = slice_ptr + (i * element_size);

                        // Read element based on its nested type
                        // Following Delve's loadArrayValues: fieldvar.loadValueInternal(recurseLevel+1, cfg)
                        let elem_value = if let Some(NestedType::Array { element_type, .. }) =
                            &field.nested_type
                        {
                            // We have element type info - recursively parse it
                            detrix_logging::debug!(
                                "[ringbuf] Parsing slice element {} with nested type",
                                i
                            );
                            parse_slice_element(
                                elem_addr,
                                element_type.as_ref(),
                                element_size,
                                config,
                                mem_reader,
                                pid,
                            )?
                        } else {
                            // Fallback: read as bytes
                            detrix_logging::debug!(
                                "[ringbuf] Slice element {} has no nested type, reading as bytes",
                                i
                            );
                            match mem_reader.read_bytes(pid, elem_addr, element_size as usize) {
                                Ok(bytes) => CapturedValue::Bytes(bytes),
                                Err(_) => CapturedValue::Error("read failed".to_string()),
                            }
                        };
                        elements.push(elem_value);
                    }

                    detrix_logging::debug!(
                        "[ringbuf] Parsed {} slice elements, creating Struct with fields",
                        elements.len()
                    );

                    CapturedValue::Struct {
                        type_name: format!("[] (len={}, cap={})", slice_len, slice_cap),
                        fields: vec![
                            (
                                "len".to_string(),
                                Box::new(CapturedValue::Scalar(slice_len)),
                            ),
                            (
                                "cap".to_string(),
                                Box::new(CapturedValue::Scalar(slice_cap)),
                            ),
                            (
                                "elements".to_string(),
                                Box::new(CapturedValue::Array {
                                    element_type: field.type_info.slice_element_type.clone(),
                                    elements,
                                }),
                            ),
                        ],
                    }
                } else {
                    // Just return slice header if no elements to read
                    CapturedValue::Slice {
                        len: slice_len,
                        cap: slice_cap,
                    }
                }
            } else if field.type_info.name == "time.Time" || field.type_info.name.ends_with(".Time")
            {
                // time.Time struct: wall uint64 (8 bytes) + ext int64 (8 bytes) + loc *Location (8 bytes) = 24 bytes
                // See $GOROOT/src/time/time.go and Delve's pkg/proc/variables.go:formatTime()
                let wall = mem_reader.read_u64(pid, field_addr).unwrap_or(0);
                let ext = mem_reader.read_u64(pid, field_addr + 8).unwrap_or(0);

                // Check if wall has monotonic bit set (bit 63)
                // Following Delve's formatTime() implementation
                let has_monotonic = (wall & (1u64 << 63)) != 0;

                // Format as human-readable datetime string
                let datetime_str = if has_monotonic {
                    // With monotonic clock: wall has 33-bit seconds since Jan 1, 1885
                    // ext has monotonic clock reading (nanoseconds since process start)
                    let sec = ((wall << 1) >> 31) as i64; // Extract 33-bit field
                    let unix_timestamp_of_wall_epoch: i64 = -2_682_288_000; // Seconds from year 1 to Jan 1, 1885
                    let unix_secs = sec + unix_timestamp_of_wall_epoch;
                    format_unix_timestamp(unix_secs)
                } else {
                    // Without monotonic clock: ext has full signed 64-bit seconds since Jan 1, year 1
                    let unix_timestamp_of_wall_epoch: i64 = -62_135_596_800; // Seconds from year 1 to 1970
                    let unix_secs = (ext as i64) + unix_timestamp_of_wall_epoch;
                    format_unix_timestamp(unix_secs)
                };

                // Capture as struct with wall, ext, and human-readable str_value
                CapturedValue::Struct {
                    type_name: "time.Time".to_string(),
                    fields: vec![
                        ("wall".to_string(), Box::new(CapturedValue::Scalar(wall))),
                        ("ext".to_string(), Box::new(CapturedValue::Scalar(ext))),
                        (
                            "str_value".to_string(),
                            Box::new(CapturedValue::String {
                                data: datetime_str.clone().into_bytes(),
                                len: datetime_str.len(),
                            }),
                        ),
                    ],
                }
            } else if field.type_info.is_array {
                // Fixed-size array: read as blob (elements stored inline)
                let blob_size = field.byte_size.min(config.max_blob_capture as u64) as usize;
                match mem_reader.read_bytes(pid, field_addr, blob_size) {
                    Ok(bytes) => CapturedValue::Bytes(bytes),
                    Err(_) => CapturedValue::Bytes(vec![0u8; blob_size]),
                }
            } else if field.type_info.name.starts_with("map[")
                || field.type_info.name.starts_with("map<")
            {
                // Map field: read the map pointer then iterate the Swiss Table.
                let map_ptr = mem_reader.read_u64(pid, field_addr).unwrap_or(0);
                if map_ptr == 0 {
                    CapturedValue::Map {
                        key_type: "?".to_string(),
                        value_type: "?".to_string(),
                        entries: vec![],
                        reason: "nil map".to_string(),
                    }
                } else {
                    let (key_nested, val_nested) = match &field.nested_type {
                        Some(NestedType::Map {
                            key_type,
                            value_type,
                            ..
                        }) => (Some(key_type.as_ref()), Some(value_type.as_ref())),
                        _ => (None, None),
                    };
                    super::map_iter::read_go_swiss_map(
                        map_ptr, key_nested, val_nested, config, mem_reader, pid,
                    )
                }
            } else if field.type_info.is_struct {
                // Embedded struct field: read bytes and recursively parse if we have type info.
                let blob_size = field.byte_size.min(config.max_blob_capture as u64) as usize;
                if let Some(crate::dwarf::nested_types::NestedType::Struct {
                    type_info: sub_type_info,
                    fields: sub_fields,
                    ..
                }) = &field.nested_type
                {
                    match mem_reader.read_bytes(pid, field_addr, blob_size) {
                        Ok(bytes) => parse_struct_fields_from_blob(
                            &bytes,
                            &sub_type_info.name,
                            sub_fields,
                            config,
                            mem_reader,
                            pid,
                        ),
                        Err(_) => CapturedValue::Bytes(vec![0u8; blob_size]),
                    }
                } else {
                    match mem_reader.read_bytes(pid, field_addr, blob_size) {
                        Ok(bytes) => CapturedValue::Bytes(bytes),
                        Err(_) => CapturedValue::Bytes(vec![0u8; blob_size]),
                    }
                }
            } else if field.type_info.is_pointer {
                // Pointer field: read the address, then dereference if we have type info.
                // Following Delve's pointer dereferencing pattern.
                let ptr_val = mem_reader.read_u64(pid, field_addr).unwrap_or(0);

                detrix_logging::debug!(
                    "[ringbuf] pointer field '{}' at {:#x} ptr={:#x} has_nested={}",
                    field_name,
                    field_addr,
                    ptr_val,
                    field.nested_type.is_some()
                );

                if ptr_val != 0 {
                    if let Some(nested) = &field.nested_type {
                        // Unwrap pointer layers to find the actual struct type
                        let mut current = nested;
                        loop {
                            match current {
                                crate::dwarf::nested_types::NestedType::Pointer {
                                    pointee, ..
                                } => {
                                    current = pointee.as_ref();
                                }
                                crate::dwarf::nested_types::NestedType::Struct {
                                    type_info,
                                    ..
                                } => {
                                    // Found the struct type - parse it with full nested type info
                                    detrix_logging::debug!(
                                        "[ringbuf] Dereferencing pointer to '{}'",
                                        type_info.name
                                    );
                                    let result = parse_struct_fields_from_addr(
                                        ptr_val,
                                        &type_info.name,
                                        config,
                                        Some(nested), // Pass the full nested type
                                        mem_reader,
                                        pid,
                                    );
                                    break result.unwrap_or_else(|e| {
                                        detrix_logging::debug!(
                                            "[ringbuf] pointer deref failed '{}' ptr={:#x}: {}",
                                            field_name,
                                            ptr_val,
                                            e
                                        );
                                        CapturedValue::Scalar(ptr_val)
                                    });
                                }
                                _ => {
                                    // Not a struct - just return the pointer value
                                    break CapturedValue::Scalar(ptr_val);
                                }
                            }
                        }
                    } else {
                        CapturedValue::Scalar(ptr_val)
                    }
                } else {
                    // Nil pointer
                    CapturedValue::Scalar(0)
                }
            } else {
                // Scalar field (int, float, bool, etc.): read from user-space
                let scalar_val = mem_reader.read_u64(pid, field_addr).unwrap_or(0);
                // Decode IEEE 754 float for float types
                let field_value = match field.type_info.name.as_str() {
                    "float64" => CapturedValue::Float(f64::from_bits(scalar_val)),
                    "float32" => CapturedValue::Float(f32::from_bits(scalar_val as u32) as f64),
                    _ => CapturedValue::Scalar(scalar_val),
                };
                field_value
            };

            fields.push((field_name, Box::new(field_value)));
        }
    } else {
        // Fallback: no DWARF struct info, just return the base address
        fields.push((
            "__base_addr".to_string(),
            Box::new(CapturedValue::Scalar(struct_base_addr)),
        ));
    }

    detrix_logging::debug!(
        "[ringbuf] Parsed {} struct fields for '{}' at {:#x}",
        fields.len(),
        type_name,
        struct_base_addr
    );

    Ok(CapturedValue::Struct {
        type_name: type_name.to_string(),
        fields,
    })
}

/// Parse struct fields directly from inline blob bytes in the ring buffer event.
///
/// Called when `VariableLocation::StackBlob` has `nested_type = Some(NestedType::Struct)`.
/// The BPF program captured the struct bytes inline into the event — no user-space
/// pointer chasing needed for scalar/pointer fields.
///
/// For string fields within the struct the blob holds `{ptr u64, len u64}`, so we
/// still call `mem_reader.read_string` to fetch the heap content.
fn parse_struct_fields_from_blob(
    blob: &[u8],
    type_name: &str,
    fields: &[crate::dwarf::nested_types::StructField],
    config: &CaptureConfig,
    mem_reader: &dyn crate::mem_reader::ProcessMemoryReader,
    pid: u32,
) -> CapturedValue {
    let mut result = Vec::new();

    for (i, field) in fields.iter().enumerate() {
        if config.max_struct_fields >= 0 && i >= config.max_struct_fields as usize {
            break;
        }

        let start = field.byte_offset as usize;
        let size = (field.byte_size as usize).min(8); // cap at 8 for scalar reads

        if start >= blob.len() {
            // Field is beyond the captured blob window
            detrix_logging::debug!(
                "[ringbuf] field '{}' at offset {} beyond blob len {}",
                field.name,
                start,
                blob.len()
            );
            break;
        }

        let field_value = if field.type_info.is_string && start + 16 <= blob.len() {
            // String header: ptr (8 bytes) + len (8 bytes) stored inline in blob
            let ptr_bytes: [u8; 8] = blob[start..start + 8].try_into().unwrap_or([0; 8]);
            let len_bytes: [u8; 8] = blob[start + 8..start + 16].try_into().unwrap_or([0; 8]);
            let ptr = u64::from_le_bytes(ptr_bytes);
            let len = u64::from_le_bytes(len_bytes) as usize;

            if ptr != 0 && len > 0 && len <= config.max_string_capture * 16 {
                match mem_reader.read_string(pid, ptr, len.min(config.max_string_capture)) {
                    Ok(s) => CapturedValue::String {
                        len: s.len(),
                        data: s.into_bytes(),
                    },
                    Err(_) => CapturedValue::String {
                        data: b"<read-failed>".to_vec(),
                        len,
                    },
                }
            } else {
                CapturedValue::String {
                    data: vec![],
                    len: 0,
                }
            }
        } else if field.type_info.is_array && field.type_info.array_element_count > 0 {
            // Fixed-size array: iterate elements and decode each
            let elem_size = field.byte_size / field.type_info.array_element_count;
            let mut elements = Vec::new();

            for elem_idx in 0..field.type_info.array_element_count {
                let elem_start = start + (elem_idx * elem_size) as usize;
                if elem_start + elem_size as usize > blob.len() {
                    break;
                }

                let elem_slice = &blob[elem_start..elem_start + elem_size as usize];
                let val = match elem_size {
                    8 => u64::from_le_bytes(elem_slice.try_into().unwrap_or([0; 8])),
                    4 => u32::from_le_bytes(elem_slice.try_into().unwrap_or([0; 4])) as u64,
                    2 => u16::from_le_bytes(elem_slice.try_into().unwrap_or([0; 2])) as u64,
                    1 => elem_slice[0] as u64,
                    _ => 0,
                };

                // Decode IEEE 754 float for float arrays
                let elem_value = match field.type_info.array_element_type.as_str() {
                    "float64" => CapturedValue::Float(f64::from_bits(val)),
                    "float32" => CapturedValue::Float(f32::from_bits(val as u32) as f64),
                    _ => CapturedValue::Scalar(val),
                };

                elements.push(elem_value);
            }

            CapturedValue::Array {
                element_type: field.type_info.array_element_type.clone(),
                elements,
            }
        } else if field.type_info.is_struct {
            // Embedded struct field (not a pointer): recursively parse the sub-blob.
            let end = (start + field.byte_size as usize).min(blob.len());
            if start >= end {
                break;
            }
            let sub_blob = &blob[start..end];

            if let Some(crate::dwarf::nested_types::NestedType::Struct {
                type_info: sub_type_info,
                fields: sub_fields,
                ..
            }) = &field.nested_type
            {
                parse_struct_fields_from_blob(
                    sub_blob,
                    &sub_type_info.name,
                    sub_fields,
                    config,
                    mem_reader,
                    pid,
                )
            } else {
                // No type info — return raw bytes
                CapturedValue::Bytes(sub_blob.to_vec())
            }
        } else if field.type_info.name.starts_with("map[")
            || field.type_info.name.starts_with("map<")
        {
            // Map field in blob: read the map pointer then iterate the Swiss Table.
            // Must come BEFORE is_pointer check since Go maps are pointers.
            let end = (start + 8).min(blob.len());
            let map_ptr = if end - start == 8 {
                u64::from_le_bytes(blob[start..end].try_into().unwrap_or([0; 8]))
            } else {
                0
            };

            if map_ptr == 0 {
                let (key_type, val_type) = parse_map_type_names(&field.type_info.name);
                CapturedValue::Map {
                    key_type,
                    value_type: val_type,
                    entries: vec![],
                    reason: "nil map".to_string(),
                }
            } else {
                let (key_nested, val_nested) = match &field.nested_type {
                    Some(NestedType::Map {
                        key_type,
                        value_type,
                        ..
                    }) => (Some(key_type.as_ref()), Some(value_type.as_ref())),
                    _ => (None, None),
                };
                super::map_iter::read_go_swiss_map(
                    map_ptr, key_nested, val_nested, config, mem_reader, pid,
                )
            }
        } else if field.type_info.is_pointer {
            // Pointer field: read 8-byte address from blob, then dereference if we have type info.
            let end = (start + 8).min(blob.len());
            let ptr_val = if end - start == 8 {
                u64::from_le_bytes(blob[start..end].try_into().unwrap_or([0; 8]))
            } else {
                0
            };

            detrix_logging::debug!(
                "[ringbuf] pointer field '{}' ptr={:#x} has_nested={}",
                field.name,
                ptr_val,
                field.nested_type.is_some()
            );

            if ptr_val != 0 {
                if let Some(nested) = &field.nested_type {
                    if find_struct_pointee(nested).is_some() {
                        // Use the address-based parser so that slice element reading,
                        // string heap reads, and nested pointer derefs all work correctly.
                        // parse_struct_fields_from_blob cannot follow slice data pointers
                        // and would return only Slice{len,cap} without elements.
                        parse_struct_fields_from_addr(
                            ptr_val,
                            &field.type_info.name,
                            config,
                            Some(nested),
                            mem_reader,
                            pid,
                        )
                        .unwrap_or_else(|e| {
                            detrix_logging::debug!(
                                "[ringbuf] pointer deref failed for '{}' ptr={:#x}: {}",
                                field.name,
                                ptr_val,
                                e
                            );
                            CapturedValue::Scalar(ptr_val)
                        })
                    } else {
                        CapturedValue::Scalar(ptr_val)
                    }
                } else {
                    CapturedValue::Scalar(ptr_val)
                }
            } else {
                // Nil pointer
                CapturedValue::Scalar(0)
            }
        } else if field.type_info.is_slice {
            // Slice field in blob: read {ptr, len, cap} header (24 bytes)
            // Go slice header: ptr (8 bytes) + len (8 bytes) + cap (8 bytes)
            if start + 24 <= blob.len() {
                let slice_ptr =
                    u64::from_le_bytes(blob[start..start + 8].try_into().unwrap_or([0; 8]));
                let slice_len =
                    u64::from_le_bytes(blob[start + 8..start + 16].try_into().unwrap_or([0; 8]));
                let slice_cap =
                    u64::from_le_bytes(blob[start + 16..start + 24].try_into().unwrap_or([0; 8]));
                detrix_logging::debug!(
                    "[ringbuf] slice field '{}' ptr={:#x} len={} cap={}, has_nested={}",
                    field.name,
                    slice_ptr,
                    slice_len,
                    slice_cap,
                    field.nested_type.is_some()
                );

                // If we have nested type info and a valid pointer, read elements
                // Following Delve's loadArrayValues pattern
                if slice_ptr != 0 && slice_len > 0 && slice_len <= 10 {
                    if let Some(NestedType::Array { element_type, .. }) = &field.nested_type {
                        let element_size = element_type.type_info().byte_size.max(1);
                        let mut elements = Vec::new();
                        for i in 0..slice_len {
                            let elem_addr = slice_ptr + (i * element_size);
                            let elem_value = parse_slice_element(
                                elem_addr,
                                element_type.as_ref(),
                                element_size,
                                config,
                                mem_reader,
                                pid,
                            )
                            .unwrap_or_else(|_| {
                                CapturedValue::Error("slice element read failed".to_string())
                            });
                            elements.push(elem_value);
                        }
                        CapturedValue::Struct {
                            type_name: format!("[] (len={}, cap={})", slice_len, slice_cap),
                            fields: vec![
                                (
                                    "len".to_string(),
                                    Box::new(CapturedValue::Scalar(slice_len)),
                                ),
                                (
                                    "cap".to_string(),
                                    Box::new(CapturedValue::Scalar(slice_cap)),
                                ),
                                (
                                    "elements".to_string(),
                                    Box::new(CapturedValue::Array {
                                        element_type: field.type_info.slice_element_type.clone(),
                                        elements,
                                    }),
                                ),
                            ],
                        }
                    } else {
                        // No nested type info - just return header
                        CapturedValue::Slice {
                            len: slice_len,
                            cap: slice_cap,
                        }
                    }
                } else {
                    CapturedValue::Slice {
                        len: slice_len,
                        cap: slice_cap,
                    }
                }
            } else {
                // Not enough bytes for slice header
                CapturedValue::Slice { len: 0, cap: 0 }
            }
        } else {
            // Scalar / other: read LE integer of appropriate size
            let end = (start + size).min(blob.len());
            let slice = &blob[start..end];
            let val = match slice.len() {
                8 => u64::from_le_bytes(slice.try_into().unwrap_or([0; 8])),
                4 => u32::from_le_bytes(slice.try_into().unwrap_or([0; 4])) as u64,
                2 => u16::from_le_bytes(slice.try_into().unwrap_or([0; 2])) as u64,
                1 => slice[0] as u64,
                _ => 0,
            };
            // Decode IEEE 754 float instead of treating as integer
            match field.type_info.name.as_str() {
                "float64" => CapturedValue::Float(f64::from_bits(val)),
                "float32" => CapturedValue::Float(f32::from_bits(val as u32) as f64),
                _ => CapturedValue::Scalar(val),
            }
        };

        result.push((field.name.clone(), Box::new(field_value)));
    }

    CapturedValue::Struct {
        type_name: type_name.to_string(),
        fields: result,
    }
}

/// Parse struct fields from ring buffer data using user-space memory reading.
///
/// DEPRECATED: Use parse_struct_fields_from_addr instead.
/// This function is kept for backward compatibility but should not be used.
#[allow(dead_code)]
fn parse_struct_fields(
    data: &[u8],
    offset: &mut usize,
    type_name: &str,
    config: &CaptureConfig,
    nested_type: Option<&crate::dwarf::nested_types::NestedType>,
    mem_reader: &dyn crate::mem_reader::ProcessMemoryReader,
    pid: u32,
) -> Result<CapturedValue> {
    // Read the struct base address from ring buffer first
    if *offset + 8 > data.len() {
        return Err(Error::RingBuffer(
            "Not enough data for struct base address".to_string(),
        ));
    }
    let struct_base_addr = read_u64(data, offset)?;

    // Delegate to the main implementation
    parse_struct_fields_from_addr(
        struct_base_addr,
        type_name,
        config,
        nested_type,
        mem_reader,
        pid,
    )
}

/// Format a Unix timestamp as a human-readable datetime string (RFC3339-like)
fn format_unix_timestamp(unix_secs: i64) -> String {
    if unix_secs < 0 {
        return format!("{} (year < 1970)", unix_secs);
    }

    let days = unix_secs / 86400;
    let remaining = unix_secs % 86400;
    let hours = remaining / 3600;
    let mins = (remaining % 3600) / 60;
    let secs = remaining % 60;

    // Simple date calculation from days since epoch
    let mut year = 1970;
    let mut d = days;
    while d >= 365 {
        let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
        let days_in_year = if leap { 366 } else { 365 };
        if d >= days_in_year {
            d -= days_in_year;
            year += 1;
        } else {
            break;
        }
    }

    let month_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
    let mut month = 1;
    let mut day = d + 1;
    for (i, &days_in_month) in month_days.iter().enumerate() {
        let actual = if i == 1 && leap { 29 } else { days_in_month };
        if day > actual {
            day -= actual;
            month += 1;
        } else {
            break;
        }
    }

    format!(
        "{:04}-{:02}-{:02} {:02}:{:02}:{:02}",
        year, month, day, hours, mins, secs
    )
}
